---
version: 2
updates:
- package-ecosystem: terraform
  directories:
  - /examples/mongodb_cluster
  - /modules/mongodb_cluster
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0  # Security-updates only
