version: 2.1
orbs:
  semver-orb: tv2norge/semver-orb@0.0.1
workflows:
  bump_version:
    jobs:
      - semver-orb/bump:
          context: org-default-build
          filters:
            branches:
              only:
                - master